### ISSUE TITLE
Possible error in temperature parsing

### ISSUE THREAD

**Issue by twicejr** [Wolfrax/WS1080#1]
Another option: weather station sensor crappy?

See my graph. I notice a sawtooth between 16.0 and 16.6, there never is a temperature reading. 
This is from 1-minute samples.
Is it a rounding error, or.... why would this happen?

Very interesting, right?
I have a WS4050 by the way, so that might also explain it. Incompatibility?
![image](https://cloud.githubusercontent.com/assets/207371/18970857/491144c8-8693-11e6-99e5-ff5b69437055.png)

**Comment by twicejr** [comment]
Oh, and I can imagine this is hard to test, it's the outside temp sensor... got a fridge around 16c ? :P

**Comment by Wolfrax** [comment]
Thanks, I have tested with my outdoor sensor (it happened to pass the interval during the weekend) and found the readings correct. As well, I rechecked the parsing (py/util.py to_signed_short) with respect to these values, should be correct.
I believe the readings are due to the sensor of your unit
